spring:
  rabbitmq:
    addresses: 192.168.31.4:5672
    username: admin
    password: admin123.
    virtual-host: /demo
    connection-timeout: 15000
#    listener:
#      simple:
#        prefetch: 1               # 限流策略：同一时间只有1条消息发送过来消费
#        acknowledge-mode: manual  # 签收模式：手动签收
#        concurrency: 5            # 基本并发：5
#        max-concurrency: 10       # 最大并发：10
  #参数格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
