spring:
  rabbitmq:
    addresses: 106.13.36.105:5680
    username: admin
    password: admin..
    virtual-host: /
    connection-timeout: 15000
    publisher-confirms: true  #启用消息确认模式
    publisher-returns: true   #
    template:
      mandatory: true
  #参数格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
