spring:
  rabbitmq:
    host: 192.168.31.4
    port: 5672
    username: admin
    password: admin123.
    virtual-host: /demo
    connection-timeout: 15000
  #    publisher-confirms: true  #启用消息确认模式
#    publisher-returns: true   #
#    template:
#      mandatory: true
  #参数格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
