#mysql
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://ovoll.cn:3308/testdb?characterEncoding=UTF-8&useSSL=false
    username: aliyun
    password: As981012.

#mybatis
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.mybatis.demo.entity
logging:
  level:
    com.example.redisdemo.dao: debug
    com.example.redisdemo.service: debug
