spring:
  rabbitmq:
    host: 47.106.121.215
    port: 5683
    username: canal
    password: canal123.
    virtual-host: /canal
    connection-timeout: 15000
    listener:
      simple:
        prefetch: 1               # 限流策略：同一时间只有1条消息发送过来消费
        acknowledge-mode: manual  # 签收模式：手动签收
        concurrency: 5            # 基本并发：5
        max-concurrency: 10       # 最大并发：10
  canal:
    host: 127.0.0.1
    port: 8081
    username: canal
    password: canal
    destination: example
